apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deploy
spec:
  selector:
    matchLabels:
      app: apache
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - name: apache
        image: muhammadadel8/muhammadadel8-apache:{{BUILD_NUMBER}}
        resources:
          requests:
             memory: 512Mi
             cpu: 0.5

---
apiVersion: v1
kind: Service
metadata:
  name: new-apache-svc
spec:
  selector:
    app: apache
  ports:
    - name: http
      port: 8080
 

  type: ClusterIP
